export {
  REMINDER_BODY_MAX_LENGTH,
  REMINDER_FIXED_DATE_PRESETS,
  REMINDER_OFFSET_OPTIONS,
  DEFAULT_REMINDER_HOUR,
  DEFAULT_REMINDER_MINUTE,
  DEFAULT_REMINDER_OFFSET,
} from '@huelmoandres/iue-shared'
