export { FollowStatus, flattenTimeline, isInternalGroup } from '@huelmoandres/iue-shared'
export type {
  ActivityStatus,
  CaseStage,
  DeadlineType,
  ExpedienteOrderByField,
  IActivityPrediction,
  ICaratulaComponents,
  ICaseStageResult,
  IDeadlineDetectionResult,
  IDecree,
  IDecreeSummary,
  IExpediente,
  IExpedienteDetail,
  IExpedientesQuery,
  IExpedienteStats,
  IInternalGroup,
  IMovement,
  IMovementClassification,
  IPaginatedExpedientes,
  IPaginatedResponse,
  MovementCategory,
  MovementPriority,
  TimelineEntry,
} from '@huelmoandres/iue-shared'
