export {
  loginSchema,
  type LoginFormData,
  type LoginFormValues,
  registerSchema,
  updateProfileSchema,
  otpSchema,
  verifyEmailSchema,
  forgotPasswordSchema,
  resetPasswordSchema,
  followExpedienteSchema,
  type RegisterFormData,
  type UpdateProfileFormData,
  type VerifyEmailFormData,
  type ForgotPasswordFormData,
  type ResetPasswordFormData,
  type FollowExpedienteFormData,
} from '@huelmoandres/iue-shared'
